# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 10:29
from __future__ import unicode_literals

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование товара')),
                ('slug', models.CharField(max_length=250, verbose_name='Наименование для ссылки')),
                ('keuw', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ключевые слова')),
                ('desk', models.CharField(blank=True, max_length=250, null=True, verbose_name='Краткое описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to=company.models.upload_to)),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Category'),
        ),
    ]
