# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20161010_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование страницы')),
                ('slug', models.CharField(max_length=50, verbose_name='Имя ссылки')),
            ],
            options={
                'verbose_name_plural': 'Страницы',
                'verbose_name': 'Страница',
            },
        ),
    ]
