# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='cena',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='dostavka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Доставка'),
        ),
    ]
