# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20161013_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='ed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Единицы измерения'),
        ),
    ]
