# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20161014_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='min_raz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Минимальный размер заказа'),
        ),
    ]
