# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_tovar_min_raz'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='nalich',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наличие'),
        ),
    ]
